version: "3.9"

services:
  # 🗄️ PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    networks:
      - uitgo

  userservice:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - uitgo

networks:
  uitgo:
