
services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - uitgo-net

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - uitgo-net

  driver-service:
    build: ./services/driver-service
    container_name: driver-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - uitgo-net

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - uitgo-net

  trip-service:
    build: ./services/trip-service
    container_name: trip-service
    ports:
      - "8082:8082"
    env_file:
      - ./services/trip-service/.env
    depends_on:
      - db
      - user-service
      - driver-service
      - payment-service
    networks:
      - uitgo-net

networks:
  uitgo-net:
    driver: bridge

volumes:
  db_data:
